# Generated by Django 4.0.6 on 2023-09-19 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=100, unique=True)),
                ('course_name', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('shash', models.CharField(blank=True, max_length=160, null=True)),
                ('createdon', models.DateTimeField(auto_now_add=True)),
                ('courses', models.ManyToManyField(blank=True, to='myapp.coursemaster', verbose_name='Courses')),
            ],
        ),
        migrations.CreateModel(
            name='CertificatesMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_name', models.CharField(max_length=200)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('email_sent', models.BooleanField(default=False)),
                ('chash', models.CharField(blank=True, max_length=160, null=True)),
                ('tid', models.CharField(blank=True, max_length=160, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.studentmaster')),
            ],
        ),
    ]
